apiVersion: apps/v1
kind: Deployment
metadata:
  name: prbasedtest
  labels:
    app: prbasedtest
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: prbasedtest
  template:
    metadata:
      labels:
        app: prbasedtest
        tier: prbasedtest
    spec:
      containers:
      - name: meow
        image: choiwyoung/prbasedtest:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          name: prbasedtest
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef: 
              name: mysql-config
              key: host
        - name: PORT
          valueFrom:
            configMapKeyRef: 
              name: mysql-config
              key: port
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: database
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: user
        - name: DB_PWD
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: user
---
apiVersion: v1
kind: Service
metadata:
  name: prbasedtest
  labels:
    app: prbasedtest
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: prbasedtest
    tier: prbasedtest
  type: LoadBalancer
