apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  type: NodePort
  ports:
  - protocol: TCP
    port: 3306
    nodePort: 31002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0.28
        ports:
        - containerPort: 3306
        env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: mysql-config
                key: host
          - name: PORT
            valueFrom:
              configMapKeyRef: 
                name: mysql-config
                key: port
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: mysql-config
                key: database
          - name: DB_USER
            valueFrom:
              configMapKeyRef:
                name: mysql-config
                key: user
          - name: DB_PWD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: password
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: password
        volumeMounts:
        - name: mysql-config
          mountPath: "/config"
          readOnly: true
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
        - name: mysql-config
          configMap:
            name: mysql-config
            items:
              - key: "host"
                path: "host"
              - key: "port"
                path: "port"
              - key: "database"
                path: "database" 
              - key: "user"
                path: "user"
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
