apiVersion: apps/v1
kind: Deployment
metadata:
  name: prbasedtest
  labels:
    app: prbasedtest
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: prbasedtest
  template:
    metadata:
      labels:
        app: prbasedtest
        tier: prbasedtest
    spec:
      containers:
      - name: meow
        image: choiwyoung/prbasedtest:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          name: prbasedtest
        env:
          - name: DB_HOST
            valueFrom: 
              secretKeyRef:
                name: db-secret
                key: host
          - name: DB_NAME
            valueFrom: 
              secretKeyRef:
                name: db-secret
                key: name
          - name: DB_USER
            valueFrom: 
              secretKeyRef:
                name: db-secret
                key: user
          - name: DB_PWD
            valueFrom: 
              secretKeyRef:
                name: db-secret
                key: password